

export const datos=
[{codgrupo:1,description:"Bebida"},
        {codgrupo:2,description:"Pan"},
        {codgrupo:3,description:"Carne"},
        {codgrupo:4,description:"Pescado"},
        {codgrupo:5,description:"Botes"},
        {codgrupo:6,description:"Vinos"},
        {codgrupo:7,description:"Refrescos"},
        {codgrupo:8,description:"Bolleria"},
        {codgrupo:9,description:"Dulces"},
        {codgrupo:10,description:"Frutas"},
        {codgrupo:11,description:"Bizcochos"},
        {codgrupo:12,description:"Pucheros"},
        {codgrupo:13,description:"Tortas"},
        {codgrupo:14,description:"Grano"},
        {codgrupo:15,description:"Pastas"},
        {codgrupo:16,description:"Ensaladas"},
        {codgrupo:17,description:"Pizzas"},
        {codgrupo:18,description:"Horno"},
        {codgrupo:19,description:"Cervezas"},
        {codgrupo:20,description:"Rebozados"},
        {codgrupo:21,description:"Frituras"},
        {codgrupo:22,description:"Yogures"},
        {codgrupo:23,description:"Helados"},
        {codgrupo:24,description:"Licores"},
        {codgrupo:25,description:"Copas"},
        {codgrupo:26,description:"Cafes"},
        {codgrupo:27,description:"Poleos"},
        {codgrupo:28,description:"Hamburguesas"},
        {codgrupo:29,description:"Chips"}];
export const mesas=[
{"codigo":"1","descripcion":"MESA 1","estaso":"-1"},
{"codigo":"2","descripcion":"MESA 2","estaso":"-1"},
{"codigo":"3","descripcion":"MESA 3","estaso":"-1"},
{"codigo":"4","descripcion":"MESA 4","estaso":"-1"},
{"codigo":"5","descripcion":"MESA 5","estaso":"-1"},
{"codigo":"6","descripcion":"MESA 6","estaso":"-1"},
{"codigo":"7","descripcion":"MESA 7","estaso":"-1"},
{"codigo":"8","descripcion":"MESA 8","estaso":"-1"},
{"codigo":"9","descripcion":"MESA 9","estaso":"-1"},
{"codigo":"10","descripcion":"MESA 10","estaso":"-1"},
{"codigo":"11","descripcion":"MESA 11","estaso":"-1"},
{"codigo":"12","descripcion":"MESA 12","estaso":"-1"},
{"codigo":"13","descripcion":"MESA 13","estaso":"-1"},
{"codigo":"14","descripcion":"MESA 14","estaso":"-1"},
{"codigo":"15","descripcion":"MESA 15","estaso":"-1"},
{"codigo":"16","descripcion":"MESA 16","estaso":"-1"},
{"codigo":"17","descripcion":"MESA 17","estaso":"-1"},
{"codigo":"18","descripcion":"MESA 18","estaso":"-1"},
{"codigo":"19","descripcion":"MESA 19","estaso":"-1"},
{"codigo":"20","descripcion":"MESA 20","estaso":"-1"},
{"codigo":"21","descripcion":"MESA 21","estaso":"-1"},
{"codigo":"22","descripcion":"MESA 22","estaso":"-1"},
{"codigo":"23","descripcion":"MESA 23","estaso":"-1"},
{"codigo":"24","descripcion":"MESA 24","estaso":"-1"},
{"codigo":"25","descripcion":"MESA 25","estaso":"0"},
{"codigo":"26","descripcion":"MESA 26","estaso":"-1"},
{"codigo":"27","descripcion":"MESA 27","estaso":"0"},
{"codigo":"28","descripcion":"MESA 28","estaso":"-1"},
{"codigo":"29","descripcion":"MESA 29","estaso":"-1"},
{"codigo":"30","descripcion":"MESA 30","estaso":"-1"},
{"codigo":"31","descripcion":"MESA 31","estaso":"0"},
{"codigo":"32","descripcion":"MESA 32","estaso":"0"},
{"codigo":"33","descripcion":"MESA 33","estaso":"0"},
{"codigo":"34","descripcion":"MESA 34","estaso":"0"},
{"codigo":"35","descripcion":"MESA 35","estaso":"-1"},
{"codigo":"36","descripcion":"MESA 36","estaso":"0"},
{"codigo":"37","descripcion":"MESA 37","estaso":"0"},
{"codigo":"38","descripcion":"MESA 38","estaso":"0"},
{"codigo":"39","descripcion":"MESA 39","estaso":"0"},
{"codigo":"40","descripcion":"MESA 40","estaso":"0"},
{"codigo":"41","descripcion":"MESA 41","estaso":"0"},
{"codigo":"42","descripcion":"MESA 42","estaso":"0"},
{"codigo":"43","descripcion":"MESA 43","estaso":"0"},
{"codigo":"44","descripcion":"MESA 44","estaso":"-1"},
{"codigo":"45","descripcion":"MESA 45","estaso":"-1"},
{"codigo":"46","descripcion":"MESA 46","estaso":"0"},
{"codigo":"47","descripcion":"MESA 47","estaso":"0"},
{"codigo":"48","descripcion":"MESA 48","estaso":"0"},
{"codigo":"49","descripcion":"MESA 49","estaso":"0"},
{"codigo":"50","descripcion":"MESA 50","estaso":"0"}
]
export const categorias=[{"codigo":"02","categoria":"REFRESCOS","ingredientes":"S"},
{"codigo":"03","categoria":"CERVEZAS","ingredientes":"N"},
{"codigo":"04","categoria":"CAF\u00C9S","ingredientes":"N"},
{"codigo":"06","categoria":"WHISKYS","ingredientes":"N"},
{"codigo":"07","categoria":"BRANDYS","ingredientes":"N"},
{"codigo":"08","categoria":"LICORES","ingredientes":"N"},
{"codigo":"13","categoria":"ENSALADA","ingredientes":"S"},
{"codigo":"15","categoria":"HAMBURGUESAS BOCATAS","ingredientes":"S"},
{"codigo":"16","categoria":"MONTADITOS","ingredientes":"S"},
{"codigo":"18","categoria":"CARNES","ingredientes":"S"},
{"codigo":"20","categoria":"POSTRES","ingredientes":"S"},
{"codigo":"22","categoria":"VINOS","ingredientes":"N"},
{"codigo":"24","categoria":"VARIOS","ingredientes":"N"},
{"codigo":"25","categoria":"CUBATA","ingredientes":"N"},
{"codigo":"26","categoria":"TAPAS","ingredientes":"S"},
{"codigo":"27","categoria":"MENU KIDS","ingredientes":"S"},
{"codigo":"28","categoria":"PATATAS","ingredientes":"S"},
{"codigo":"29","categoria":"TOSTADAS Y PANES","ingredientes":"S"},
{"codigo":"30","categoria":"PESCADO","ingredientes":"S"},
{"codigo":"31","categoria":"DEL MAR","ingredientes":"S"},
{"codigo":"32","categoria":"ARROZ","ingredientes":"S"},
{"codigo":"33","categoria":"ITALIANO","ingredientes":"S"},
{"codigo":"34","categoria":"SOPAS","ingredientes":"S"}
]
export const articulos=[
{"codigo":"2","descripcion":"COCA-COLA","categoria":"02"},
{"codigo":"3","descripcion":"COCA-COLA LIGHT","categoria":"02"},
{"codigo":"4","descripcion":"FANTA NARANJA","categoria":"02"},
{"codigo":"5","descripcion":"FANTA LIM\u00D3N","categoria":"02"},
{"codigo":"8","descripcion":"SPRITE","categoria":"02"},
{"codigo":"9","descripcion":"TONICA","categoria":"02"},
{"codigo":"10","descripcion":"BITTER KAS","categoria":"02"},
{"codigo":"11","descripcion":"RED BULL","categoria":"02"},
{"codigo":"12","descripcion":"AGUA PEQUE\u00D1A","categoria":"02"},
{"codigo":"14","descripcion":"AGUA GRANDE","categoria":"02"},
{"codigo":"17","descripcion":"ZUMO PI\u00D1A","categoria":"02"},
{"codigo":"18","descripcion":"ZUMO MELOCOT\u00D3N","categoria":"02"},
{"codigo":"19","descripcion":"AQUARIUS NARANJA","categoria":"02"},
{"codigo":"20","descripcion":"AQUARIUS LIM\u00D3N","categoria":"02"},
{"codigo":"21","descripcion":"NESTEA","categoria":"02"},
{"codigo":"22","descripcion":"CASERA","categoria":"02"},
{"codigo":"23","descripcion":"CHOLECK","categoria":"02"},
{"codigo":"26","descripcion":"AGUA VICHY","categoria":"02"},
{"codigo":"293","descripcion":"ZUMO NARANJA NATURAL","categoria":"02"}
]